### ISSUE TITLE
X42 plugin - stepseq with more functions?

### ISSUE THREAD

**Issue by khz-LAW** [x42/stepseq.lv2#11]
Would it be possible to equip a sequencer with the following functions?
Personally I would find it very musical if the sequencer

Global:
- Swing
- Directions (…/forward/reverse/alternate/pendulum/random/brownian/eitherway/…)
- Timebase (1/2/4/8/16/32/64/2T/4T/8T716T/32T/64T)
- Bar Length
- Sync
- ReSync
- (Force to) Scale
- .

Per row:
- First Step
-  Last Step
- …

Individual for every note:
- Velocity
- Length
- Delay
- Probabilities / Accumulator Events
- …

would support.

I got to know and appreciate these functions through the Cirklon

http://files.sequentix.com/cirklon-manual-1.18-draft.pdf#%5B%7B%22num%22%3A81%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C26%2C365%2C0%5D

http://files.sequentix.com/cirklon-manual-1.18-draft.pdf#%5B%7B%22num%22%3A112%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C65%2C676%2C0%5D

THX && cheers
khz

**Comment by falkTX** [comment]
stepseq already syncs to the host (and thus other sequencers).
swing is there already, and velocity per note as well.
have you tried the plugin yet?

**Comment by x42** [comment]
No further development is planned for this plugin.

It is mainly constrained by its use of fixed ports which is mandatory for it to run on the [MOD](https://www.moddevices.com/).
A flexible, more powerful version would have to break that, and other plugins are pioneering that. https://github.com/sjaehn/BSEQuencer for example.
