### ISSUE TITLE
Add step count UI control

### ISSUE THREAD

**Issue by AS383** [x42/stepseq.lv2#2]
A some way to specify step count at edit time will be useful. For example xN multiplayer in style of step duration control.

**Comment by x42** [comment]
The plugin was designed for a fixed step count, mainly to work around limitations imposed by the MOD host.

While the sequencer engine was prepared, but a variable step count would have to be implemented as completely different plugin (using Atom message ports).

https://github.com/sjaehn/BSEQuencer  got there first, just use that plugin instead for new projects.
