### ISSUE TITLE
Dynamic step count?

### ISSUE THREAD

**Issue by simonvanderveldt** [x42/stepseq.lv2#3]
Would it be somehow possible to have a dynamic step count?
I.e. for instance 1 of stepseq.lv2 I want 8 steps, but for instance 2 I want 32 steps.

**Comment by x42** [comment]
Not dynamic but you can compile the plugin multiple times e.g.
`make N_NOTES=8 N_STEPS=16 clean all`
and then
 `cp -a build ~/.lv2/stepseq-8x16.lv2`

long term some better solution will be needed.

**Comment by simonvanderveldt** [comment]
> Not dynamic but you can compile the plugin multiple times e.g.
> make N_NOTES=8 N_STEPS=16 clean all
> and then
> cp -a build ~/.lv2/stepseq-8x16.lv2

Yeah, that's what I'm doing now, was wondering if you had some idea on how to address this :)
Would it technically be possible to have one plugin that can dynamically change it's step and note count?

**Comment by unfa** [comment]
I've tried building a 16x32 version, but failed:

```
$ make N_NOTES=16 N_STEPS=32 clean all
Version: 0.5.7-1 -> 0 5 7 1
LV2 Version: 1295 3
Makefile:125: *** jack application only support 8x8 grid
rm -f build/manifest.ttl build/stepseq.ttl \
        build/stepseq.so \
        build/stepseqUI_gl.so
rm -rf build/*.dSYM
rm -rf x42/x42-*
rm -rf build/modgui
rm -f modgui/icon-stepseq.html modgui/style-stepseq.css modgui/box.png
test -d x42/ && rmdir x42/ || true
test -d build/ && rmdir build/ || true
test -d .git -a .gitmodules -a -f Makefile.git && make -f Makefile.git submodule_check
make[1]: Entering directory '/data/Applications/stepseq.lv2'
make[1]: Leaving directory '/data/Applications/stepseq.lv2'
sed "s/@LV2NAME@/stepseq/g;s/@URISUFFIX@/s32n16/;s/@LIB_EXT@/.so/" \
  lv2ttl/manifest.ttl.in > build/manifest.ttl
sed "s/@LV2NAME@/stepseq/g;s/@URISUFFIX@/s32n16/;s/@LIB_EXT@/.so/;s/@UI_TYPE@/ui:X11UI/;s/@LV2GUI@/stepseqUI_gl/g" \
        lv2ttl/manifest.gui.in >> build/manifest.ttl
sed "s/@LV2NAME@/stepseq/g;s/@SIGNATURE@//;s/@NAMESUFFIX@/32x16/;s/@URISUFFIX@/s32n16/;s/@VERSION@/lv2:microVersion 3 ;lv2:minorVersion 1295 ;/g;s/@UITTL@/ui:ui stepseq:ui_gl ;/;s/@MODBRAND@//;s/@MODLABEL@//;s/@STEPS@/32/" \
        lv2ttl/stepseq.ttl.in > build/stepseq.ttl
./gridgen.sh 16 32 >> build/stepseq.ttl
*** NO BOX BACKGROUND FOR 32 steps, 16 notes
*** compile misc/boxmaker for this build-host
*** make -C misc boxmaker
make: *** [Makefile:243: build/stepseq.ttl] Error 1
```

**Comment by x42** [comment]
Read the output:
```
*** NO BOX BACKGROUND FOR 32 steps, 16 notes
*** compile misc/boxmaker for this build-host
*** make -C misc boxmaker
```
then run `make -C misc boxmaker` and try again `make N_NOTES=16 N_STEPS=32 clean all`

**Comment by x42** [comment]
> Would it technically be possible to have one plugin that can dynamically change it's step and note count?

Yes, but that'll need a bit of a re-design.

The current concept was for initially made for the MOD, which only support simple control ports.
mod-host does not support Atom Ports to pass messages from/to the GUI, nor state-extension.
The only way to have automatable controls and remember the settings was using N * M fixed ports.

For a _desktop_ version, it'll be a lot simpler to just use message-passing via LV2 Atoms (patch set/get messages). The playback engine itself mostly fine and prepared for variable step count.
Still it'll be a bit of work, in particular the UI.

**Comment by unfa** [comment]
Oh wow, it works! Thank you!
Sorry, I got overwhelmed by the output and was unable to understand what it said.

Is there a way to build the plug-in under a new name so that I can have multiple version installed on my system without name collisions?

**Comment by x42** [comment]
>Is there a way to build the plug-in under a new name so that I can have multiple version installed on my system without name collisions?

Different configurations have different names and URIs already, and can be installed in parallel.
However you have to manually copy the `build` folder to a unique location (or manually merge the manifest files).

e.g. 

```
make N_NOTES=16 N_STEPS=32 clean all
mkdir -p ~/.lv2
cp -a build ~/.lv2/stepseq-32x16.lv2
make N_NOTES=16 N_STEPS=16 clean all
cp -a build ~/.lv2/stepseq-16x16.lv2
lv2ls  | grep stepseq
```

**Comment by x42** [comment]
...just use https://github.com/sjaehn/BSEQuencer
