### ISSUE TITLE
misc/Makefile missing in 0.6.0 release

### ISSUE THREAD

**Issue by danielappelt** [x42/stepseq.lv2#8]
misc/Makefile is missing in v0.6.0.tar.gz. The file is necessary to build the plugin for specific number of steps and notes.

**Comment by x42** [comment]
What tar.gz? I don't provide dist tar balls

**Comment by danielappelt** [comment]
Github seems to create [a release for every tag](https://github.com/x42/stepseq.lv2/releases) you create automatically. It's quite handy if it works right. It's strange though that it is missing the mentioned file.

**Comment by x42** [comment]
Aah, I wish there was a way to disable github releases.
Those also don't include submodules, so it's not working anyway. 

PS. it's not strange the file is explicitly excluded in the `.gitattributes`.
The plugin's version is also only correctly set when it's compiled from a full git clone. `git describe` needs to work.  (or when it's bundled in https://github.com/x42/x42-plugins, a dedicated version file is created)

**Comment by danielappelt** [comment]
Okay! Yesterday, I built some different note&step versions by manually including mentioned Makefile and robtk. The plugins seemed to work just fine in Ardour. I didn't check the version numbers though!

If I go for a version / tag checkout from the repository what would `make submodules` do? Would it always fetch head from robtk?

**Comment by x42** [comment]
> If I go for a version / tag checkout from the repository what would make submodules do? Would it always fetch head from robtk?

No. `make submodule` just calls  init+update:
https://github.com/x42/stepseq.lv2/blob/0a6421b9a440a8bed1d590b402f373800b54c7bd/Makefile.git#L3-L5

It's only needed once, the default `make` [all] updates existing submodules if needed, but does not initialize them. Since init/update requires network access it is not done by default. Only after a user has at least once manually initialized the repo.  This helps distro packagers.

**Comment by danielappelt** [comment]
Sorry, to ask another question regarding the matter. The implications of your last comment are not immediately clear to me.

If I build a certain version of stepseq.lv2 now and then do the exact same process for the same version a year from now, does it mean that most probably different versions of robtk will be used in the process as robtk progresses? Should I care?

**Comment by x42** [comment]
> If I build a certain version of stepseq.lv2 now and then do the exact same process for the same version a year from now, does it mean that most probably different versions of robtk will be used in the process as robtk progresses? 

Only if you `git pull` the main repository before building. Submodule updates require a commit.

> Should I care?

No :)  updates are usually good.

**Comment by danielappelt** [comment]
Thank you! This conversation reminded me to not rely on platform features (like automatic Github releases) that may be dropped in the next platform release.
